[book]
authors = ["@rscarson"]
language = "en"
multilingual = false
src = "src"
title = "Rustyscript Documentation"

[output.html]
[output.html.playground]
runnable = false

[preprocessor.image-size]
command = "mdbook-image-size"