name: Test Rust Examples

on:
  workflow_run:
    workflows:
      - Update Examples
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Update examples on master
      run: cargo run --bin generate_examples -- --snapshot-only

    - name: Run tests
      run: cargo run --bin run_test rust