name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Update examples on master
      run: cargo run --bin generate_examples

    # Commit and push changes if there are any using GITHUB_TOKEN 
    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add examples js_examples || true
        git diff --cached --quiet || git commit -m "Update examples" && git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Test rust examples
      run: cargo run --bin run_test rust